export const userdata = [
  {
    id: 1,
    serialNumber: "1",
    role: "Test Engineer",
    userName: "User123",
    deviceCount: 5,
    bucketName: "Bucket1",
    email: "user123@example.com",
    lastLogin: "2024-03-03 12:00:00",
    status: "Active",
    action: "Reapprove",
    roleName: "CXO",
    permission: "Lorem Ipsum is simply dummy text of the printing",
    description:
      "Test Case Hub, Test Plan Hub, Test Schedule Hub, Results and Reports",
    testcaseId: "TC-202",
    testcaseName: "Test Case 2",
    userRole: "Device Engineer",
    userName: "Soni Sharma",
    DUTRequired: "1",
    category: "Download Policy",
    duration: "23:10",
    execTestcaseID: "1933",
    feature: "THROUGHPUT_IPERF",
    iteration: "45",
    estTime: "36",
    status: "Pass",
    testcase_ID: "TC-001",
    testcase_Name: "Test Case 1",
    Category: "Functional",
    Timestamp: "2024-06-02 10:49:14",
    Status: "Passed",
    Logs_File: "log_1.txt",
    Reason: "Invalid Input",
  },
  {
    id: 2,
    serialNumber: "2",
    userName: "User456",
    role: "Test Engineer",
    deviceCount: 3,
    bucketName: "Bucket2",
    email: "user456@example.com",
    lastLogin: "2024-03-02 14:30:00",
    status: "Inactive",
    action: "Reapprove",
    roleName: "NOC Engineer",
    permission: "Lorem Ipsum is simply dummy text of the printing",
    description:
      "Test Case Hub, Test Plan Hub, Test Schedule Hub, Results and Reports",

    testcaseId: "TC-202",
    testcaseName: "Test Case 2",
    userRole: "Device Engineer",
    userName: "Soni Sharma",
    DUTRequired: "1",
    category: "Download Policy",
    duration: "23:10",

    execTestcaseID: "1933",
    feature: "THROUGHPUT_IPERF",
    iteration: "45",
    estTime: "36",
    status: "Pass",

    testcase_ID: "TC-001",
    testcase_Name: "Test Case 1",
    Category: "Functional",
    Timestamp: "2024-06-02 10:49:14",
    Status: "Passed",
    Logs_File: "log_1.txt",
    Reason: "Invalid Input",
  },
  {
    id: 3,
    serialNumber: "3",
    userName: "User789",
    role: "Test Engineer",
    deviceCount: 8,
    bucketName: "Bucket3",
    email: "user789@example.com",
    lastLogin: "2024-03-01 10:45:00",
    status: "Active",
    action: "Reapprove",

    roleName: "OEM Engineer",
    permission: "Lorem Ipsum is simply dummy text of the printing",
    description:
      "Test Case Hub, Test Plan Hub, Test Schedule Hub, Results and Reports",

    testcaseId: "TC-202",
    testcaseName: "Test Case 2",
    userRole: "Device Engineer",
    userName: "Soni Sharma",
    DUTRequired: "1",
    category: "Download Policy",
    duration: "23:10",

    execTestcaseID: "1933",
    feature: "THROUGHPUT_IPERF",
    iteration: "45",
    estTime: "36",
    status: "Pass",

    testcase_ID: "TC-001",
    testcase_Name: "Test Case 1",
    Category: "Functional",
    Timestamp: "2024-06-02 10:49:14",
    Status: "Passed",
    Logs_File: "log_1.txt",
    Reason: "Invalid Input",
  },
  {
    id: 4,
    serialNumber: "4",
    userName: "User101",
    role: "Test Engineer",
    deviceCount: 2,
    bucketName: "Bucket4",
    email: "user101@example.com",
    lastLogin: "2024-02-28 18:20:00",
    status: "Inactive",
    action: "Reapprove",
    roleName: "Test Engineer",
    permission: "Lorem Ipsum is simply dummy text of the printing",
    description:
      "Test Case Hub, Test Plan Hub, Test Schedule Hub, Results and Reports",

    testcaseId: "TC-202",
    testcaseName: "Test Case 2",
    userRole: "Device Engineer",
    userName: "Soni Sharma",
    DUTRequired: "1",
    category: "Download Policy",
    duration: "23:10",

    execTestcaseID: "1933",
    feature: "THROUGHPUT_IPERF",
    iteration: "45",
    estTime: "36",
    status: "Pass",

    testcase_ID: "TC-001",
    testcase_Name: "Test Case 1",
    Category: "Functional",
    Timestamp: "2024-06-02 10:49:14",
    Status: "Passed",
    Logs_File: "log_1.txt",
    Reason: "Invalid Input",
  },
  {
    id: 5,
    serialNumber: "5",
    userName: "User202",
    role: "Test Engineer",
    deviceCount: 7,
    bucketName: "Bucket5",
    email: "user202@example.com",
    lastLogin: "2024-02-27 21:55:00",
    status: "Active",
    action: "Reapprove",
    roleName: "Admin Test Engineer",
    permission: "Lorem Ipsum is simply dummy text of the printing",
    description:
      "Test Case Hub, Test Plan Hub, Test Schedule Hub, Results and Reports",

    testcaseId: "TC-202",
    testcaseName: "Test Case 2",
    userRole: "Device Engineer",
    userName: "Soni Sharma",
    DUTRequired: "1",
    category: "Download Policy",
    duration: "23:10",

    execTestcaseID: "1933",
    feature: "THROUGHPUT_IPERF",
    iteration: "45",
    estTime: "36",
    status: "Pass",

    testcase_ID: "TC-001",
    testcase_Name: "Test Case 1",
    Category: "Functional",
    Timestamp: "2024-06-02 10:49:14",
    Status: "Passed",
    Logs_File: "log_1.txt",
    Reason: "Invalid Input",
  },
  {
    id: 6,
    serialNumber: "6",
    userName: "User303",
    role: "Test Engineer",
    deviceCount: 4,
    bucketName: "Bucket6",
    email: "user303@example.com",
    lastLogin: "2024-02-26 15:10:00",
    status: "Inactive",
    action: "Reapprove",
    roleName: "Admin OEM Engineer",
    permission: "Lorem Ipsum is simply dummy text of the printing",
    description:
      "Test Case Hub, Test Plan Hub, Test Schedule Hub, Results and Reports",

    testcaseId: "TC-202",
    testcaseName: "Test Case 2",
    userRole: "Device Engineer",
    userName: "Soni Sharma",
    DUTRequired: "1",
    category: "Download Policy",
    duration: "23:10",

    execTestcaseID: "1933",
    feature: "THROUGHPUT_IPERF",
    iteration: "45",
    estTime: "36",
    status: "Pass",

    testcase_ID: "TC-001",
    testcase_Name: "Test Case 1",
    Category: "Functional",
    Timestamp: "2024-06-02 10:49:14",
    Status: "Passed",
    Logs_File: "log_1.txt",
    Reason: "Invalid Input",
  },
  {
    id: 7,
    serialNumber: "7",
    userName: "User404",
    role: "Test Engineer",
    deviceCount: 6,
    bucketName: "Bucket7",
    email: "user404@example.com",
    lastLogin: "2024-02-25 09:30:00",
    status: "Active",
    action: "Reapprove",
    roleName: "Admin CXO",
    permission: "Lorem Ipsum is simply dummy text of the printing",
    description:
      "Test Case Hub, Test Plan Hub, Test Schedule Hub, Results and Reports",

    testcaseId: "TC-202",
    testcaseName: "Test Case 2",
    userRole: "Device Engineer",
    userName: "Soni Sharma",
    DUTRequired: "1",
    category: "Download Policy",
    duration: "23:10",

    execTestcaseID: "1933",
    feature: "THROUGHPUT_IPERF",
    iteration: "45",
    estTime: "36",
    status: "Pass",

    testcase_ID: "TC-001",
    testcase_Name: "Test Case 1",
    Category: "Functional",
    Timestamp: "2024-06-02 10:49:14",
    Status: "Passed",
    Logs_File: "log_1.txt",
    Reason: "Invalid Input",
  },
  {
    id: 8,
    serialNumber: "8",
    userName: "User505",
    role: "Test Engineer",
    deviceCount: 1,
    bucketName: "Bucket8",
    email: "user505@example.com",
    lastLogin: "2024-02-24 17:40:00",
    status: "Inactive",
    action: "Reapprove",

    roleName: "Role Name",
    permission: "Lorem Ipsum is simply dummy text of the printing",
    description:
      "Test Case Hub, Test Plan Hub, Test Schedule Hub, Results and Reports",

    testcaseId: "TC-202",
    testcaseName: "Test Case 2",
    userRole: "Device Engineer",
    userName: "Soni Sharma",
    DUTRequired: "1",
    category: "Download Policy",
    duration: "23:10",

    execTestcaseID: "1933",
    feature: "THROUGHPUT_IPERF",
    iteration: "45",
    estTime: "36",
    status: "Pass",

    testcase_ID: "TC-001",
    testcase_Name: "Test Case 1",
    Category: "Functional",
    Timestamp: "2024-06-02 10:49:14",
    Status: "Passed",
    Logs_File: "log_1.txt",
    Reason: "Invalid Input",
  },
  {
    id: 9,
    serialNumber: "9",
    userName: "User606",
    role: "Test Engineer",
    deviceCount: 9,
    bucketName: "Bucket9",
    email: "user606@example.com",
    lastLogin: "2024-02-23 20:05:00",
    status: "Active",
    action: "Reapprove",

    roleName: "Role Name",
    permission: "Lorem Ipsum is simply dummy text of the printing",
    description:
      "Test Case Hub, Test Plan Hub, Test Schedule Hub, Results and Reports",

    testcaseId: "TC-202",
    testcaseName: "Test Case 2",
    userRole: "Device Engineer",
    userName: "Soni Sharma",
    DUTRequired: "1",
    category: "Download Policy",
    duration: "23:10",

    execTestcaseID: "1933",
    feature: "THROUGHPUT_IPERF",
    iteration: "45",
    estTime: "36",
    status: "Pass",

    testcase_ID: "TC-001",
    testcase_Name: "Test Case 1",
    Category: "Functional",
    Timestamp: "2024-06-02 10:49:14",
    Status: "Passed",
    Logs_File: "log_1.txt",
    Reason: "Invalid Input",
  },
  {
    id: 10,
    serialNumber: "10",
    userName: "User707",
    role: "Test Engineer",
    deviceCount: 3,
    bucketName: "Bucket10",
    email: "user707@example.com",
    lastLogin: "2024-02-22 11:15:00",
    status: "Inactive",
    action: "Reapprove",
    roleName: "Role Name",
    permission: "Lorem Ipsum is simply dummy text of the printing",
    description:
      "Test Case Hub, Test Plan Hub, Test Schedule Hub, Results and Reports",

    testcaseId: "TC-202",
    testcaseName: "Test Case 2",
    userRole: "Device Engineer",
    userName: "Soni Sharma",
    DUTRequired: "1",
    category: "Download Policy",
    duration: "23:10",

    execTestcaseID: "1933",
    feature: "THROUGHPUT_IPERF",
    iteration: "45",
    estTime: "36",
    status: "Pass",

    testcase_ID: "TC-001",
    testcase_Name: "Test Case 1",
    Category: "Functional",
    Timestamp: "2024-06-02 10:49:14",
    Status: "Passed",
    Logs_File: "log_1.txt",
    Reason: "Invalid Input",
  },
];

const GroupListingData = [
  {
    id: 1,
    serialNumber: 1,
    bucketName: "Bucket1",
    description: "Description1",
    numOfUsers: 10,
  },
  {
    id: 2,
    serialNumber: 2,
    bucketName: "Bucket2",
    description: "Description2",
    numOfUsers: 15,
  },
  {
    id: 3,
    serialNumber: 3,
    bucketName: "Bucket3",
    description: "Description3",
    numOfUsers: 20,
  },
  {
    id: 4,
    serialNumber: 4,
    bucketName: "Bucket4",
    description: "Description4",
    numOfUsers: 8,
  },
  {
    id: 5,
    serialNumber: 5,
    bucketName: "Bucket5",
    description: "Description5",
    numOfUsers: 25,
  },
  {
    id: 6,
    serialNumber: 6,
    bucketName: "Bucket6",
    description: "Description6",
    numOfUsers: 12,
  },
  {
    id: 7,
    serialNumber: 7,
    bucketName: "Bucket7",
    description: "Description7",
    numOfUsers: 18,
  },
  {
    id: 8,
    serialNumber: 8,
    bucketName: "Bucket8",
    description: "Description8",
    numOfUsers: 14,
  },
  {
    id: 9,
    serialNumber: 9,
    bucketName: "Bucket9",
    description: "Description9",
    numOfUsers: 22,
  },
  {
    id: 10,
    serialNumber: 10,
    bucketName: "Bucket10",
    description: "Description10",
    numOfUsers: 30,
  },
];

export default GroupListingData;

export const bucketUserListData = [
  {
    id: 1,
    serialNumber: 1,
    userName: "John Doe",
    deviceCount: 3,
    email: "john.doe@example.com",
    lastLogin: "2024-03-03 10:30 AM",
    status: "Active",
    action: "Reapprove",
  },
  {
    id: 2,
    serialNumber: 2,
    userName: "Jane Smith",
    deviceCount: 2,
    email: "jane.smith@example.com",
    lastLogin: "2024-03-02 04:45 PM",
    status: "Inactive",
    action: "Reapprove",
  },
  {
    id: 3,
    serialNumber: 3,
    userName: "Alice Johnson",
    deviceCount: 5,
    email: "alice.johnson@example.com",
    lastLogin: "2024-03-01 08:15 AM",
    status: "Active",
    action: "Reapprove",
  },
  {
    id: 4,
    serialNumber: 4,
    userName: "Bob Williams",
    deviceCount: 1,
    email: "bob.williams@example.com",
    lastLogin: "2024-02-29 12:00 PM",
    status: "Inactive",
    action: "Reapprove",
  },
  {
    id: 5,
    serialNumber: 5,
    userName: "Eve Brown",
    deviceCount: 4,
    email: "eve.brown@example.com",
    lastLogin: "2024-02-28 02:30 PM",
    status: "Active",
    action: "Reapprove",
  },
];

export const deviceData = [
  {
    key: "1",
    serialNumber: "1",
    deviceId: "D12345",
    imei: "123456789012345",
    phoneNumber: "+1234567890",
    grantDevice: "Yes",
    lock: "No",
    carrierName: "Carrier A",
    mccMnc: "310260",
    apn: "internet",
  },
  {
    key: "2",
    serialNumber: "2",
    deviceId: "D67890",
    imei: "987654321098765",
    phoneNumber: "+0987654321",
    grantDevice: "No",
    lock: "Yes",
    carrierName: "Carrier B",
    mccMnc: "310270",
    apn: "web",
  },
  {
    key: "3",
    serialNumber: "3",
    deviceId: "D11111",
    imei: "111111111111111",
    phoneNumber: "+1111111111",
    grantDevice: "Yes",
    lock: "No",
    carrierName: "Carrier C",
    mccMnc: "310280",
    apn: "data",
  },
  {
    key: "4",
    serialNumber: "4",
    deviceId: "D22222",
    imei: "222222222222222",
    phoneNumber: "+2222222222",
    grantDevice: "No",
    lock: "Yes",
    carrierName: "Carrier D",
    mccMnc: "310290",
    apn: "net",
  },
  {
    key: "5",
    serialNumber: "5",
    deviceId: "D33333",
    imei: "333333333333333",
    phoneNumber: "+3333333333",
    grantDevice: "Yes",
    lock: "No",
    carrierName: "Carrier E",
    mccMnc: "310300",
    apn: "vpn",
  },
  {
    key: "6",
    serialNumber: "6",
    deviceId: "D44444",
    imei: "444444444444444",
    phoneNumber: "+4444444444",
    grantDevice: "No",
    lock: "Yes",
    carrierName: "Carrier F",
    mccMnc: "310310",
    apn: "proxy",
  },
  {
    key: "7",
    serialNumber: "7",
    deviceId: "D55555",
    imei: "555555555555555",
    phoneNumber: "+5555555555",
    grantDevice: "Yes",
    lock: "No",
    carrierName: "Carrier G",
    mccMnc: "310320",
    apn: "lan",
  },
  {
    key: "8",
    serialNumber: "8",
    deviceId: "D66666",
    imei: "666666666666666",
    phoneNumber: "+6666666666",
    grantDevice: "No",
    lock: "Yes",
    carrierName: "Carrier H",
    mccMnc: "310330",
    apn: "wifi",
  },
  {
    key: "9",
    serialNumber: "9",
    deviceId: "D77777",
    imei: "777777777777777",
    phoneNumber: "+7777777777",
    grantDevice: "Yes",
    lock: "No",
    carrierName: "Carrier I",
    mccMnc: "310340",
    apn: "broadband",
  },
  {
    key: "10",
    serialNumber: "10",
    deviceId: "D88888",
    imei: "888888888888888",
    phoneNumber: "+8888888888",
    grantDevice: "No",
    lock: "Yes",
    carrierName: "Carrier J",
    mccMnc: "310350",
    apn: "isp",
  },
];

export const event = [
  {
    id: 0,
    title: "No. of Devices: 12\nTC : TC27",
    start: new Date(2021, 6, 13, 12, 0, 0),
    end: new Date(2021, 6, 13, 14, 0, 0),
  },
  {
    id: 1,
    title: "No. of Devices: 8\nTC : TC19",
    start: new Date(2021, 6, 14, 9, 0, 0),
    end: new Date(2021, 6, 14, 11, 0, 0),
  },
  {
    id: 2,
    title: "No. of Devices: 15\nTC : TC33",
    start: new Date(2021, 6, 15, 10, 0, 0),
    end: new Date(2021, 6, 15, 12, 0, 0),
  },
  {
    id: 3,
    title: "No. of Devices: 20\nTC : TC44",
    start: new Date(2021, 6, 16, 14, 0, 0),
    end: new Date(2021, 6, 16, 16, 0, 0),
  },
  {
    id: 4,
    title: "No. of Devices: 10\nTC : TC21",
    start: new Date(2021, 6, 17, 13, 0, 0),
    end: new Date(2021, 6, 17, 15, 0, 0),
  },
  {
    id: 5,
    title: "No. of Devices: 7\nTC : TC18",
    start: new Date(2021, 6, 18, 11, 0, 0),
    end: new Date(2021, 6, 18, 13, 0, 0),
  },
  {
    id: 6,
    title: "No. of Devices: 25\nTC : TC50",
    start: new Date(2021, 6, 19, 15, 0, 0),
    end: new Date(2021, 6, 19, 17, 0, 0),
  },
  {
    id: 7,
    title: "No. of Devices: 30\nTC : TC55",
    start: new Date(2021, 6, 20, 16, 0, 0),
    end: new Date(2021, 6, 20, 18, 0, 0),
  },
  {
    id: 8,
    title: "No. of Devices: 18\nTC : TC29",
    start: new Date(2021, 6, 21, 14, 0, 0),
    end: new Date(2021, 6, 21, 16, 0, 0),
  },
  {
    id: 9,
    title: "No. of Devices: 22\nTC : TC39",
    start: new Date(2021, 6, 22, 13, 0, 0),
    end: new Date(2021, 6, 22, 15, 0, 0),
  },
  {
    id: 10,
    title: "No. of Devices: 14\nTC : TC24",
    start: new Date(2021, 6, 23, 10, 0, 0),
    end: new Date(2021, 6, 23, 12, 0, 0),
  },
  {
    id: 11,
    title: "No. of Devices: 27\nTC : TC58",
    start: new Date(2021, 6, 24, 9, 0, 0),
    end: new Date(2021, 6, 24, 11, 0, 0),
  },
  {
    id: 12,
    title: "No. of Devices: 9\nTC : TC20",
    start: new Date(2021, 6, 25, 13, 0, 0),
    end: new Date(2021, 6, 25, 15, 0, 0),
  },
  {
    id: 13,
    title: "No. of Devices: 31\nTC : TC60",
    start: new Date(2021, 6, 26, 14, 0, 0),
    end: new Date(2021, 6, 26, 16, 0, 0),
  },
  {
    id: 14,
    title: "No. of Devices: 16\nTC : TC30",
    start: new Date(2021, 6, 27, 15, 0, 0),
    end: new Date(2021, 6, 27, 17, 0, 0),
  },
  {
    id: 15,
    title: "No. of Devices: 23\nTC : TC40",
    start: new Date(2021, 6, 28, 11, 0, 0),
    end: new Date(2021, 6, 28, 13, 0, 0),
  },
  {
    id: 16,
    title: "No. of Devices: 29\nTC : TC52",
    start: new Date(2021, 6, 29, 10, 0, 0),
    end: new Date(2021, 6, 29, 12, 0, 0),
  },
];
export const testcaseresult = [
  {
    "s.no": 1,
    "Testcase ID": "TC-001",
    "Testcase Name": "Test Case 1",
    Category: "Functional",
    Timestamp: "2024-06-02 10:49:14",
    Status: "Passed",
    "Logs File": "log_1.txt",
    Reason: "Invalid Input",
  },
  {
    "s.no": 2,
    "Testcase ID": "TC-002",
    "Testcase Name": "Test Case 2",
    Category: "Security",
    Timestamp: "2024-06-13 10:49:14",
    Status: "Skipped",
    "Logs File": "log_2.txt",
    Reason: "Assertion Error",
  },
  {
    "s.no": 3,
    "Testcase ID": "TC-003",
    "Testcase Name": "Test Case 3",
    Category: "Usability",
    Timestamp: "2024-06-18 10:49:14",
    Status: "Skipped",
    "Logs File": "log_3.txt",
    Reason: "Timeout",
  },
  {
    "s.no": 4,
    "Testcase ID": "TC-004",
    "Testcase Name": "Test Case 4",
    Category: "Performance",
    Timestamp: "2024-06-11 10:49:14",
    Status: "Passed",
    "Logs File": "log_4.txt",
    Reason: "Invalid Input",
  },
  {
    "s.no": 5,
    "Testcase ID": "TC-005",
    "Testcase Name": "Test Case 5",
    Category: "Security",
    Timestamp: "2024-06-23 10:49:14",
    Status: "Failed",
    "Logs File": "log_5.txt",
    Reason: "Timeout",
  },
  {
    "s.no": 6,
    "Testcase ID": "TC-006",
    "Testcase Name": "Test Case 6",
    Category: "Usability",
    Timestamp: "2024-06-06 10:49:14",
    Status: "Skipped",
    "Logs File": "log_6.txt",
    Reason: "N/A",
  },
  {
    "s.no": 7,
    "Testcase ID": "TC-007",
    "Testcase Name": "Test Case 7",
    Category: "Security",
    Timestamp: "2024-06-02 10:49:14",
    Status: "Failed",
    "Logs File": "log_7.txt",
    Reason: "Invalid Input",
  },
  {
    "s.no": 8,
    "Testcase ID": "TC-008",
    "Testcase Name": "Test Case 8",
    Category: "Usability",
    Timestamp: "2024-06-22 10:49:14",
    Status: "Failed",
    "Logs File": "log_8.txt",
    Reason: "N/A",
  },
  {
    "s.no": 9,
    "Testcase ID": "TC-009",
    "Testcase Name": "Test Case 9",
    Category: "Performance",
    Timestamp: "2024-06-24 10:49:14",
    Status: "Failed",
    "Logs File": "log_9.txt",
    Reason: "Assertion Error",
  },
  {
    "s.no": 10,
    "Testcase ID": "TC-010",
    "Testcase Name": "Test Case 10",
    Category: "Security",
    Timestamp: "2024-06-16 10:49:14",
    Status: "Skipped",
    "Logs File": "log_10.txt",
    Reason: "N/A",
  },
];
