export const userList = "User Management";
export const addUser = "Add";
export const addSErver = "Add";
export const editUser = "Edit User";
export const Explore_our = "Explore our";
export const assign_to_Bucket = "Assign to Bucket";
export const Network_KPI_Monitoring_Tool = "Bussiness";
export const login = "Login";
export const sign_up = "Sign up";
export const add_new_user = "Add";
export const Declined_Approval = "Pending Approval";
export const Access_Management = "Access Management";
export const Role_List = "Role List";
export const Test_Hub = "Testcase Hub";
export const Testcase = "Testcases";
export const My_Device_List = "My Device List";

export const Save_Details = "Save Details";
export const CHECK_DEVICE_AVAILABILITY = "Device Availability";
export const SCHEDULE_CALENDER ="Schedule & Execute"
export const TEST_RESULT_HUB = "Test Case Result";
export const DOWNLOAD_SUMMARY = "Download Summary";
export const TEST_PLAN_RESULT = "Test Plan Result";
export const DASHBOARD = 'Dashboard';
export const ADMIN_DASHBOARD = 'Admin Dashboard';
export const USERS = 'Users';
export const DEVICES = 'Devices';
export const EXECUTED_TEST_RESULTS = 'Executed Test Results';
export const SCHEDULED_TESTS = 'Test Hub';
export const CHOOSE_YOUR_PREFERENCE = 'Choose your preference';
export const MO_MT_VOICE_CALL_SUCCESS='MO-MT Voive call Success';
export const MO_MT_VOICE_CALL_DROP  = 'MO-MT Voive call Drop';
export const MOBILITY_VOICE_CALL_SUCCESS ='Mobility Voice call Success';
export const MOBILITY_VOICE_CALL_DROP ='Mobility Voice call Drop'
export const ADD_ROLE ="Add";
