export const products = [
    {
      id: 1,
      name: 'Baxter PrisMax CRRT Machine',
      brand: 'Baxter',
      model: 'PrisMax',
      description: 'The PrisMax System is designed to give healthcare professionals more confidence in the delivery of continuous renal replacement therapy (CRRT) and therapeutic plasma exchange (TPE) therapies.',
      features: [
        'Fluid Scale Range: 0 to 11 Kg',
        'Accuracy: 0–5200 g: ±7.0 g',
        'Syringe Size: 20 to 50 ml',
        'Continuous delivery rate range: 0.5 to 5 ml/h',
        'Ultrasonic air detector: Detects single air bubble >20 µl',
        'Height: 140 to 170 cm',
        'Width: Approx. 51 cm',
      ],
      image: 'https://renalcare.baxter.com/sites/g/files/ebysai1226/files/styles/social_media_share/public/2020-04/prismax-570x700px.jpg',
    },
    {
      id: 2,
      name: 'Fresenius Multifiltrate CRRT Dialysis Machine',
      brand: 'Fresenius Medical',
      model: 'Multifiltrate',
      description: 'The Fresenius multifiltrate CRRT dialysis machine is designed to be easy and comfortable to use for everyone. It provides a full range of renal replacement therapies to patients.',
      features: [
        'Power: Electric',
        'Accuracy: 99%',
        'Frequency: 50 – 60Hz',
        'Arterial Pressure: -280 to +300 mm Hg',
        'Venous Pressure: -80 to +500 mm Hg',
        'Display: 10.4” TFT-LCD',
        'Weight: Approx. 100Kg',
      ],
      image: 'https://www.freseniusmedicalcare.asia/files/img/products/acute/fresenius-multifiltrate-dialysis.jpg',
    },
    {
      id: 3,
      name: 'B Braun Diapact CRRT Machine',
      brand: 'B Braun',
      model: 'Diapact',
      description: 'The Diapact System is designed to offer freedom in all therapies at any time with high fluid exchange accuracy and safety features for total fluid management.',
      features: [
        'Integrated Fluid Heater: 20 to 39°C',
        'Heparin Pump (perfusion)',
        'Load cell capacity: Up to 25 l',
        'Height: Approx. 140 cm',
        'Weight: Approx. 80Kg',
      ],
      image: 'https://www.bbraun.com/content/dam/catalog/bbraun/bbraunProductCatalog/S/AEM2015/en-GB/iv-st5304-di-diadyalysisinfrastructurer-systemimages-1-jpg--denverdiadialysisinfrastructurer-2560x1440.jpg',
    },
    {
      id: 4,
      name: 'Nipro Surdial 55 Plus Dialysis Machine',
      brand: 'Nipro',
      model: 'Surdial 55 Plus',
      description: 'The Surdial 55 Plus Dialysis Machine provides innovative technology for easy handling and safety in dialysis treatments.',
      features: [
        'Turnable touch panel display',
        'Single needle system with one clamp',
        'Weight: 72Kg',
        'Power Supply: 230 V/AC 110 V ±10%',
        'Battery Backup: 0.5Hr',
      ],
      image: 'https://www.nipro-group.com/sites/default/files/2021-01/surdial-55-plus.png',
    },
    {
      id: 5,
      name: 'Fresenius 4008A Dialysis Machine',
      brand: 'Fresenius Medical',
      model: '4008A',
      description: 'The Fresenius 4008A dialysis machine incorporates high therapy standards while minimizing costs, making dialysis more accessible to patients.',
      features: [
        'Power: 220V',
        'Weight: 90Kg',
        'Inlet Pressure: 4 BAR',
        'Water Inlet Temperature: 4 BAR',
        'Frequency: 50Hz',
      ],
      image: 'https://www.freseniusmedicalcare.asia/files/img/products/chronic/dialysis/fresenius-4008a.jpg',
    },
  ];
  